name: CI

on:
  push:
    branches: [main, 'feature/**', 'hotfix/**', 'release/**']
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint & Typecheck
        run: pnpm lint && pnpm typecheck

      - name: Unit tests (Vitest)
        run: pnpm test -- --coverage

      - name: Build recipes.sqlite (ETL + Zod validation)
        run: pnpm etl:build

      - name: Build app
        run: pnpm build

  e2e:
    if: github.event_name == 'pull_request' || startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build app
        run: pnpm build

      - name: Install Playwright Browsers
        uses: microsoft/playwright-github-action@v1

      - name: Run E2E (wizard + offline)
        run: pnpm test:e2e
